### ISSUE TITLE
A question about particle display  from a college girl

### ISSUE THREAD

**Issue by LiuLiuJerry** [ramakarl/fluids3#4]
Hi,
    I am a college student from Beijing Forestry University,China. I want to learn something about fluid simulation for graphics and have been studing your code for sometime.I have left a message on your website but didn't recieve youe reply. Guess you didn't check you website for a long time, so i leave my questions here.
    The first thing i have to say is , it's really a fantastic work and i have learned a lot through reading it.
    However, i am faced with a question that , the particles are not showing up unless the display mode is sprite, in other words, all i can see is black backgounds when the DRAWMODE is not 1.besides, the 2D parts are showing well.
    Another program developed based on this using glee and freeglut is running well. I am using win7 and CUDA5.5, Opengl4.3.Can you help me solving this ?
    thank you very much !
    Jerry Liu

**Comment by ramakarl** [comment]
To Jerry Liu,

Hi. I will be traveling to china in June for business and holiday, so I 
will not have much time to look at code during this time. The latest 
version of Fluids v.3 does not use glee or freeglut, so it should not 
have any other dependency other than opengl. I believe that the other 
drawmodes are not fully tested, because there are so many particles the 
sprite method is fastest. Why do you need some other draw mode? I would 
be able to take a closer look at these issues in july. In the meantime, 
I hope that you are able to find some solutions from your effort. I 
would be interested to know what is your application for forestry.

Regards,
Rama Hoetzlein

**Comment by LiuLiuJerry** [comment]
Hi, 
 Thank you .I have find a way to show the particles in VBO method. All i have to do is get the GL_TEXTURE_2D disabled. The reason remains to be found. I am preparing for my final exam and havn't been studing it for several days.
 My application is  to simulate the freezing process of water on a tree. In fact i would rather call it an exercise, for my fundamental purpose is to learn the knowledge of computer graphics in practice.
Your work opened my eyes when I knew nothing about computer animation.So, if you are comming to Beijing during your travel, and if you want , i would be glad to intruduce you some attractions~

Regards,
Jerry

**Comment by ramakarl** [comment]
Hi Jerry,

I am glad you found a way to show the particles. If you still have some 
issue, let me know more details.

I will be in Beijing from June 7 to 11th.
Which university do you attend? If you would like, we could meet briefly 
to talk in or near your campus at a cafe.
I am happy to meet students which take some new interest in computer 
graphics, and look forward to understand more about your application goal.

Regards,
Rama

**Comment by LiuLiuJerry** [comment]
Hi Rama,
    It's really a surprise that i will see the author of fluids soon! 
    My univercity is Beijing Forestry Univercity, It has the best landscape and forestry major in China.It is located in Haidian District, east side of Tsinghua Univercity.
    I will be free from June 8 to 11th. If you have planed to be there during those time ,we can meet whenever you like .
    Besides, if you don't mind, i want to show you my teammate,too, He studies graphics together with me to simulate ice.
    One important thing is that he has been preparing for the IELTS test for months, so he can speak English more fluently than me. Infact, i am afraid that we will  spend  a tough time understanding  each other due to my poor English, even with his help. So maybe i will start learning some professional vocabulary for a better conmmunication.Don't laugth at me~
    Anyway , Welcome to China!

Regards,
Jerry

At 2016-06-03 02:16:46, "Rama Hoetzlein" notifications@github.com wrote:
Hi Jerry,

I am glad you found a way to show the particles. If you still have some
issue, let me know more details.

I will be in Beijing from June 7 to 11th.
Which university do you attend? If you would like, we could meet briefly
to talk in or near your campus at a cafe.
I am happy to meet students which take some new interest in computer
graphics, and look forward to understand more about your application goal.

Regards,
Rama

**Comment by rchoetzlein** [comment]
Dear Jerry,

Hi. I can meet you and your friend on thursday or friday.
Lets make the arrangement of place and time with my friend Ying,
her phone # is 15010380261. You can also txt her your contact number.
We can figure out the time together.

Regards,
Rama

**Comment by suxg32732** [comment]
@LiuLiuJerry could you tell me Which graphics are you using? i'm using win7,  GTX1060,  but i can't intall cuda5.5, thanks.

**Comment by ramakarl** [comment]
Hi Jerry,

Nice to talk to you again. The GTX 1060 card has the newer 'pascal' 
chip, so it would require CUDA 6.1 or higher. I think if you try the 
latest cuda then it should work. Make sure you have most recent driver also.
Is this to run fluids v.3?

I mention in a previous email that I am working on a new project called 
GVDB Voxels, which comes with a sample that can do the same things as 
fluid. This could be useful for you because it can also render the surface.
If you would like, you can get early access to GVDB by joining the Beta 
program.
Just click on button "Register for early access to GVDB Sparse Volumes 
SDK" located on this page:
http://developer.nvidia.com/gvdb
This gvdb is actually easier to build than fluids.

Hope your studies are going well!

Regards,
  Rama

**Comment by sensboston** [comment]
@suxg32732, please check my comment at https://github.com/rchoetzlein/fluids3/issues/3
If you don't know how to extract dlls from msi package I can help you (but still have no idea - is it legal to send extracted dlls to someone?)

**Comment by suxg32732** [comment]
@sensboston  I'm glad to tell you that my problem has been solved, whatever, thanks you。

**Comment by suxg32732** [comment]
I'm glad to tell you that my problem has been solved, whatever, thank you。
